// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values ensure the app works even if .env is not present during deploy
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://ncznkhjveugqtnienxbp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jem5raGp2ZXVncXRuaWVueGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1NDE2NDIsImV4cCI6MjA4NTExNzY0Mn0.apCg_Qz9d4qJm8-G1DVxzJwLdKnVRjMnQxFeFp1XTGE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});